version: '3.8'

services:
  # 1. Aplicación Web (FastAPI + NiceGUI)
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Construye la URL de conexión usando las variables del .env
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MOODLE_API_URL=https://tuaulavirtual.ut.edu.co/webservice/rest/server.php
      - MOODLE_API_TOKEN=${MOODLE_API_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    # Opcional: Para que veas cambios en tu código sin reiniciar
    volumes:
      - ./app:/app/app

  # 2. Worker de Celery (Procesa el Excel en segundo plano)
  worker:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A app.core.celery_app worker --loglevel=info
    environment:
      # Misma URL de base de datos dinámica
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MOODLE_API_URL=https://tuaulavirtual.ut.edu.co/webservice/rest/server.php
      - MOODLE_API_TOKEN=${MOODLE_API_TOKEN}
    depends_on:
      - redis
      - db
    volumes:
      - ./app:/app/app

  # 3. Base de Datos (Diario de Operaciones)
  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # Aquí lee las credenciales que definiste en el .env
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  # 4. Cola de Mensajes (Para Celery)
  redis:
    image: redis:6-alpine

volumes:
  postgres_data: