version: '3.8'

services:
  # 1. Aplicación Web (FastAPI + NiceGUI)
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Variables críticas para el Entrypoint (start.sh)
      - CONTAINER_ROLE=web
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      
      # Variables de la Aplicación
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MOODLE_API_URL=https://tuaulavirtual.ut.edu.co/webservice/rest/server.php
      - MOODLE_API_TOKEN=${MOODLE_API_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    # Montaje corregido para coincidir con el COPY . . del Dockerfile
    volumes:
      - ./:/app

  # 2. Worker de Celery (Procesa el Excel en segundo plano)
  worker:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    # ELIMINADO: command: celery ... (Ahora el control lo tiene start.sh)
    environment:
      # Variables críticas para el Entrypoint (start.sh)
      - CONTAINER_ROLE=worker
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis

      # Variables de la Aplicación
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MOODLE_API_URL=https://tuaulavirtual.ut.edu.co/webservice/rest/server.php
      - MOODLE_API_TOKEN=${MOODLE_API_TOKEN}
    depends_on:
      - redis
      - db
    volumes:
      - ./:/app

  # 3. Base de Datos (Diario de Operaciones)
  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  # 4. Cola de Mensajes (Para Celery)
  redis:
    image: redis:6-alpine

volumes:
  postgres_data: